version: "3.8"
services:
  db:
    image: postgres:latest
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: lymondgl
      POSTGRES_USER: lymondgl
      POSTGRES_DB: lymondgl
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lymondgl" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
