"""alter

Revision ID: f3a5dae6dad8
Revises: 7f6a99643695
Create Date: 2023-03-27 00:01:48.050064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a5dae6dad8'
down_revision = '7f6a99643695'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('borrow_user_id_key', 'borrow', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('borrow_user_id_key', 'borrow', ['user_id'])
    # ### end Alembic commands ###
